name: Build Packer Image

on:
  push:
    paths:
      - 'packer-images/**'

jobs:
  build-packer-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Configure HCP Packer Authentication
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
        run: |
          echo "export HCP_CLIENT_ID=${HCP_CLIENT_ID}" >> $GITHUB_ENV
          echo "export HCP_CLIENT_SECRET=${HCP_CLIENT_SECRET}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV

      - name: Initialize Packer
        working-directory: ./packer-image
        run: packer init .

      - name: Build Packer Image
        working-directory: ./packer-image
        run: packer build .
